version : '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT-PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=lobbyservice
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3307:3306"
  lobbyservice-application-container:
      image: lobbyservice
      ports:
          - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/lobbyservice?autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: ""
      build:
        context: "./"
        dockerfile: "Dockerfile"
      depends_on:
        - mysql-standalone